# Generated by Django 4.1.1 on 2022-09-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('country', models.CharField(default='', max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('team', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stadiums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(default='', max_length=30)),
                ('stadium', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
